=== vlad-avr/OOP_Labs/Lab2/demo/Schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="greenhouse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="flower" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:all minOccurs="1" maxOccurs="1">
                            <xs:element type="xs:string" name="name" />
                            <xs:element name="soil">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="podzol" />
                                        <xs:enumeration value="turf_podzol" />
                                        <xs:enumeration value="regular" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:string" name="origin" />
                            <xs:element name="visuals">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="stalk_length">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:double">
                                                    <xs:minExclusive value="0" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="color" />
                                        <xs:element name="flower_diameter">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:double">
                                                    <xs:minExclusive value="0" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="tips">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="temperature">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:double">
                                                    <xs:minInclusive value="0" />
                                                    <xs:maxInclusive value="50" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="illumination">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="0" />
                                                    <xs:maxInclusive value="24" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element type="xs:unsignedShort" name="irrigation" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="reproduction">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="leaves" />
                                        <xs:enumeration value="stalks" />
                                        <xs:enumeration value="seeds" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute type="xs:ID" name="id" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vlad-avr/OOP_Labs/Lab 2/demo/Test.xml
<?xml version="1.0" encoding="UTF-8"?>
<greenhouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Schema.xsd">
 <flower id="ID-1">
    <name>Tulip</name>
    <soil>podzol</soil>
    <origin>Netherlands</origin>
    <visuals>
       <stalk_length>30</stalk_length>
       <color>red</color>
       <flower_diameter>10</flower_diameter>
    </visuals>
    <tips>
       <temperature>18</temperature>
       <illumination>7</illumination>
       <irrigation>10</irrigation>
    </tips>
    <reproduction>leaves</reproduction>
 </flower>
 <flower id="ID-2">
    <name>Rose</name>
    <soil>turf_podzol</soil>
    <origin>England</origin>
    <visuals>
       <stalk_length>150</stalk_length>
       <color>deep-red</color>
       <flower_diameter>15</flower_diameter>
    </visuals>
    <tips>
       <temperature>20</temperature>
       <illumination>7</illumination>
       <irrigation>100</irrigation>
    </tips>
    <reproduction>stalks</reproduction>
 </flower>

</greenhouse>
